export * from './create-client.prisma.repository'
export * from './delete-vehicle.prisma.repository'
export * from './find-all-clients.prisma.repository'
export * from './find-client-by-condition.prisma.repository'
export * from './find-client-by-id.prisma.repository'
export * from './find-client-by-social-number.prisma.repository'
export * from './update-client.prisma.repository'
