export * from './client.interface'
export * from './create-client.interface'
export * from './delete-client.interface'
export * from './find-client-by-condition.interface'
export * from './find-client-by-id.interface'
export * from './find-client-by-social-number.interface'
export * from './update-client.interface'
